[project]
name = "lazy-github"
description = "A terminal UI for interacting with Github"
version = "0.1"


license = { file = "LICENSE"}

requires-python = ">=3.11"
dependencies = [
	"PyGithub",
	"httpx",
	"pydantic",
	"textual",
	"textual-dev",
]

[project.optional-dependencies]
checks = [
	"pyright",
	"ruff",
]

[project.scripts]
lazy-github = "lazy_github:main"


[tool.ruff]

line-length = 120
