name: Publish the package to pypi

on: workflow_dispatch

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lazy-github
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: yezz123/setup-uv@v4
      # Build the distribution
    - name: Build lazy-github distribution
      run: uvx hatch build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
  notify:
    name: Notify when this workflow completes (regardless of success or failure)
    if: ${{ always() }}
    needs:
      - pypi-publish
    runs-on: ubuntu-latest
    steps:
      - uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
            
